GCC = g++
FLAGS = -Wall -Werror
main:
	${GCC} ${FLAGS} src/breakerbot.cpp -o main -lmraa

pots:
	${GCC} ${FLAGS} src/breakerbot.cpp -o pots -lmraa

stop:
	${GCC} ${FLAGS} src/breakerbot.cpp -o stop -lmraa

clean:
	rm bin/*
